name: DSi-DDR
on:
  push:
    branches:
    - master
jobs:
  build-nds:
    runs-on: ubuntu-latest
    container: skyly29/blocksds:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Compile
      run: |
        make -f Makefile
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: dsi-DDR
        path: |
          *.nds
