name: Diva-OSX-14
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Compile
      run: |
        make -f Makefile-Diva-Mac
    - name: Create tarball
      run: |
        tar -cvf ddr.tgz ddr
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: Artifact
        path: |
          ./ddr
